site_name: Hourly

nav:
  - Home: index.md
  - Invoicing: Payments.md
  - Time Estimation: README.ipynb
  - Compensation: Compensation.md
  - WorkLog: WorkLog.md
  - FAQ: FAQ.md
  - Press release: press-release.md
  - Author's notes: about.md
  
theme: material

use_directory_urls: false

plugins:
  - mknotebooks
  - search

markdown_extensions:
  - toc:
      permalink: "#"
  - codehilite
  - admonition
  - markdown_include.include

